spring.application.name=currency-exchange
spring.config.import=optional:configserver:http://localhost:8888
server.port=8000

spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:testMicroservicedb
spring.jpa.defer-datasource-initialization=true

eureka.instance.prefer-ip-address=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

resilience4j.retry.instances.sample-api.max-attempts=5

resilience4j.retry.instances.sample-api.wait-duration=10
resilience4j.retry.instances.sample-api.enable-exponential-backoff=true

resilience4j.ratelimiter.instances.default.limit-for-period=2
resilience4j.ratelimiter.instances.default.limit-refresh-period=10s

#what should be the interval between Retries.So if an API call is failing, I would wait for a little while and then make the API call again.I can configure how much time to wait for. The configuration is waitDuration

# The other thing you can also configure is exponential back off. What is exponential back off?Let's configure it and see it in action.enableExponentialBackoff off is equal to trueand save this. that the response takes a little bit more time.Why is it taking a little bit more time?Because each subsequent request bit would wait for a little longer.What do I mean? that the first Retry happened after one second.The second Retry happened after one and a half seconds.The third Retry happened after almost two and a half seconds.And the next Retry took about four seconds,almost four seconds.

#So you can see that each subsequent Retry is taking longer and longer and that's why is called exponential back off.

#So whenever you are working on the cloud, for example AWS, and you are working with some API, most of the APIs use exponential back off.So if I'm calling an API and the first attempt is failing, what it would do is it would make the next attempt after let's say one second.The subsequent attempt that the third attempt will be made after two seconds.and that's one of the features that the resilience Retry also supports.


#These are useful when a service is momentary down, you just give the service a little bit of time and then call it again.

#However, what if the service is really down for a long time? That's the kind of scenarios where we would go for a circuit breaker pattern.